version: '3'

services:
  nodes:
    image: darchlabs/nodes # using image name tag
    depends_on:
      - postgres
      - redis
    restart: always
    env_file:
      - ./node.env
    restart: on-failure
    ports:
      - "8545-8595:8545-8595"
      - "6969:6969"
    volumes:
      - ../data:/home/nodes/data:rw
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ../data/redis:/data-redis:rw

  postgres:
    image: postgres:13
    ports:
    - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

