version: '3'

services:
  ethereum-node:
    image: ethereum-node # using image name tag
    env_file:
      - ./node.env
    restart: on-failure
    ports:
      - "8545:8545"
      - "6969:6969"
    volumes:
      - ../data/ethereum:/home/node/data:rw

