package config

var ETHNodesMethods = map[string]bool{
	"eth_blockNumber":                         true,
	"eth_call":                                true,
	"eth_chainId":                             true,
	"eth_estimateGas":                         true,
	"eth_gasPrice":                            true,
	"eth_getBalance":                          true,
	"eth_getBlockByHash":                      true,
	"eth_getBlockByNumber":                    true,
	"eth_getBlockReceipts":                    true,
	"eth_getBlockTransactionCountByHash":      true,
	"eth_getBlockTransactionCountByNumber":    true,
	"eth_getCode":                             true,
	"eth_getFilterChanges":                    true,
	"eth_getFilterLogs":                       true,
	"eth_getLogs":                             true,
	"eth_getStorageAt":                        true,
	"eth_getTransactionByBlockHashAndIndex":   true,
	"eth_getTransactionByBlockNumberAndIndex": true,
	"eth_getTransactionByHash":                true,
	"eth_getTransactionCount":                 true,
	"eth_getTransactionReceipt":               true,
	"eth_getUncleCountByBlockHash":            true,
	"eth_getUncleCountByBlockNumber":          true,
	"eth_mining":                              true,
	"eth_newBlockFilter":                      true,
	"eth_newFilter":                           true,
	"eth_newPendingTransactionFilter":         true,
	"eth_sendRawTransaction":                  true,
	"eth_signTransaction":                     true,
	"eth_subscribe":                           true,
	"eth_syncing":                             true,
	"eth_unsubscribe":                         true,
}
