apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodes
  namespace: default
spec:
  selector:
    matchLabels:
      role: nodes
  template:
    metadata:
      labels:
        role: nodes
    spec:
      containers:
      - name: nodes
        image: darchlabs/nodes
        imagePullPolicy: Never
        ports:
        - containerPort: 6969
        readinessProbe:
          httpGet:
            path: /api/v2/health
            port: 6969
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 6969
          initialDelaySeconds: 1
          periodSeconds: 5
        env:
          - name: ENVIRONMENT
            value: "development"
          - name: API_SERVER_PORT
            value: "6969"
          - name: BASE_PATH_DATABASE
            value: "data"
          - name: NETWORKS_URL
            value: "ethereum:capable-quick-vineyard.discover.quiknode.pro/3f240555880826d7153fe818e34bf1aef2b75e50,polygon:skilled-misty-morning.matic.discover.quiknode.pro/9c6b0efce65cc906fec0275ac85da2385a8d8359"
          - name: REDIS_URL
            value: "redis:6397"

---
apiVersion: v1
kind: Service
metadata:
  name: nodes
spec:
  ports:
  - port: 6969
    targetPort: 6969
  selector:
    role: nodes

#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
  #name: deployment-manager-user
  #namespace: default

#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: Role
#metadata:
  #namespace: default
  #name: deployment-manager
#rules:
#- apiGroups: ["*"] 
  #resources: ["pods"]
  #verbs: ["get", "watch", "list", "create", "delete", "update", "patch"]

#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
  #name: deployment-manager-binding
  #namespace: default
#subjects:
#- kind: ServiceAccount
  #name: deployment-manager-user
  #namespace: default
#roleRef:
  #kind: Role
  #name: deployment-manager
  #apiGroup: "rbac.authorization.k8s.io"

