apiVersion: apps/v1 ## Chainlink Node
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      volumes:
        - name: shared-data
          hostPath:
            path: /usr/src/shared-data

      initContainers:
          - name: chainlink-creds-creator
            image: busybox:latest
            #command: ["/bin/sh", "-c"]
            #args: ["echo ThisPasswordIsSecure >> $HOME/password.txt && sleep 20898098098"]
            args:
              - /bin/sh
              - -c
              - |
                echo "CREATING PWD FILE" &&
                echo "ThisPasswordIsSecure" >> $HOME/password.txt &&
                sleep 10
            volumeMounts:
              - name: shared-data
                mountPath: $HOME/

      containers:
        - name: ubuntu
          image: ubuntu:latest
          command: ["/bin/sh", "-c"]
          args: ["apt-get update && /bin/sleep 3650d"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-data
              mountPath: $HOME/
      restartPolicy: Always
